# Google Cloud Build Configuration for Medical Coding Intelligence Platform
# Automated build and deployment to Cloud Run

steps:
  # Step 1: Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/medical-coding-app:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/medical-coding-app:latest'
      - '.'
  
  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/medical-coding-app:$BUILD_ID'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/medical-coding-app:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'medical-coding-app'
      - '--image=gcr.io/$PROJECT_ID/medical-coding-app:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--concurrency=100'
      - '--max-instances=10'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-secrets=OPENAI_API_KEY=openai-api-key:latest,UMLS_API_KEY=umls-api-key:latest,PINECONE_API_KEY=pinecone-api-key:latest,LOINC_USERNAME=loinc-username:latest,LOINC_PASSWORD=loinc-password:latest'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/medical-coding-app:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/medical-coding-app:latest'

# Build options
options:
  # Use higher-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Increase timeout for frontend build
  timeout: '1200s'
  
  # Use Docker layer caching for faster builds
  logging: CLOUD_LOGGING_ONLY

# Substitutions (can be overridden)
substitutions:
  _SERVICE_NAME: medical-coding-app
  _REGION: us-central1