[providers]
# Use both Node.js and Python
node = "18.17.0"
python = "3.10"

[phases.setup]
nixPkgs = ["nodejs", "npm", "python310", "python310Packages.pip"]

[phases.install]
cmds = [
    "cd frontend && npm ci --production",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build] 
cmds = [
    "cd frontend && npm run build",
    "mkdir -p backend/static",
    "cp -r frontend/build/* backend/static/"
]

[start]
cmd = "python -m uvicorn backend.server:app --host 0.0.0.0 --port $PORT"