[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m uvicorn backend.server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production", ENVIRONMENT = "production" }

[environments.staging]
variables = { NODE_ENV = "staging", ENVIRONMENT = "staging" }